export default {
    "common_key": "Rusty Key",
    "full_energy_potion": "Flask of Rejuvenation",
    "kings_guard_sword": "Kings Guard",
    "unlock_wallet": "Unlock your wallet",
    "equip": "Equip",
    "unequip": "Unequip",
    "common": "Common",
    "resource": "Resource",
    "axe": "Axe",
    "legendary": "Legendary",
    "full_energy_potion_desc": "Restores 100% of Energy.",
    "kings_guard_sword_desc": "A gift from the King.",
    "common_key_desc": "A little bit rusty.",
    "attack": "Attack",
    "defense": "Defense",
    "dodge": "Dodge",
    "energy": "Energy",
    "presale-chest-0": "Rookie",
    "presale-chest-1": "Lieutenant",
    "presale-chest-2": "Knight",
    "presale-chest-3": "King",
    "continue_from_gacha": "TAP TO CONTINUE",
    "open_next": "OPEN NEXT",
    "button-open": "Open",
    "transfer-chests": "Transfer chests",
    "time-left": "Time Left",
    "raid-view": "Raid",
    "try-again": "Try again",
    "unknown-error-msg": "Unexpected error.",
    "challenges": "Challenges",
    "rewards": "Rewards",
    "damage-short": "DMG",
    "tier": "Tier",
    "dkt-bonus": "DKT Bonus:",
    "damage-done": "Damage Done",
    "slots-avaialble": "Slots",
    "raid-reward-title": "{boss} was defeated!",
    "continue": "Continue",
    "claim-reward": "Claim",
    "raid-victory": "Victory!",
    "raid-lose": "The time ran out! {boss} escaped.",
    "loot-tier": "Current Loot Tier {tier}",
    "combat-log": "Combat Log",
    "refill-hint-message": "Refill it now?",
    "no-health-title": "Not enough health!",
    "no-stamina-title": "Not enough stamina!",
    "no-energy-title": "Not enough energy!",
    "do-refill": "Refill now",
    "health-refill-title": "Restore health",
    "energy-refill-title": "Restore energy",
    "stamina-refill-title": "Restore stamina",
    "refill-message": "Choose refill method",
    "player-raid-killed-title": "You died",
    "player-raid-killed-message": "{boss} killed you. Restore your health to get back to combat.",
    "TopDamageDealers": "Highest Damage",
    "TopDamageDealers-desc": "Be in the top to gain additional rewards.",
    "LastHit": "Last Hit",
    "LastHit-desc": "Be the last one who strikes the boss and earn additional rewards!",
    "leaderboard": "Leaderboard",
    "highscore-you-mark": "(You)",
    "unlock-wallet": "Unlock your wallet.",
    "no-wallet": "There is no Tron Wallet connected to your browser."
}; 