export default {
    "common_key": "Rusty Key",
    "full_energy_potion": "Flask of Rejuvenation",
    "kings_guard_sword": "Kings Guard",
    "unlock_wallet": "Unlock your wallet",
    "equip": "Equip",
    "unequip": "Unequip",
    "common": "Common",
    "resource": "Resource",
    "axe": "Axe",
    "legendary": "Legendary",
    "full_energy_potion_desc": "Restores 100% of Energy.",
    "kings_guard_sword_desc": "A gift from the King.",
    "common_key_desc": "A little bit rusty.",
    "attack": "Attack",
    "defense": "Defense",
    "dodge": "Dodge",
    "energy": "Energy",
    "presale-chest-0": "Rookie",
    "presale-chest-1": "Lieutenant",
    "presale-chest-2": "Knight",
    "presale-chest-3": "King",
    "continue_from_gacha": "TAP TO CONTINUE",
    "open_next": "OPEN NEXT",
    "button-open": "Open",
    "transfer-chests": "Transfer chests"
};